ck/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import home_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls', namespace='home')),
    path('', home_view, name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, re_path
from .views import login_view, logout_view, register_view, home_view, event_view, profile_view, listing_view, \
    detail_view, enquire_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'home'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('event/', event_view, name='event'),
    path('add_event/', views.add_event, name='add_event'),
    path('profile/', profile_view, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/enquire/', enquire_view, name='enquire'),
    path('listings/', listing_view, name='listings'),
    path('listings/details/<int:pk>/', detail_view, name='details'),
    path('add_property/', views.add_property, name='add_property'),
    path('edit_property/<int:pk>/', views.edit_property, name='edit_property'),
    path('', home_view, name='home'),
    path('search/', views.property_search, name='property_search'),
    path('report/', views.generate_report, name='generate_report'),
    path('remove_listing/<int:property_id>/', views.remove_listing, name='remove_listing'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone


class PropertyType(models.Model):
    id = models.AutoField(primary_key=True)
    property_type_name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.property_type_name)


class PropertyNeighborhood(models.Model):
    id = models.AutoField(primary_key=True)
    property_neighborhood_name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.property_neighborhood_name)


class PropertyPricerange(models.Model):
    id = models.AutoField(primary_key=True)
    property_price_range_name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.property_price_range_name)


class Property(models.Model):
    STATUS_CHOICES = (
        ('available', 'AVAILABLE'),
        ('pending', 'PENDING'),
        ('sold', 'SOLD'),
    )

    PROPERTY_CHOICES = (
        (True, 'Yes'),
        (False, 'No')
    )
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='none')
    description = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=3, decimal_places=1)
    square_feet = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    featured_property = models.BooleanField(choices=PROPERTY_CHOICES, default='False')
    flag = models.BooleanField(default=True)
    property_image_main = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=False)
    property_image_1 = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    property_image_2 = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    property_image_3 = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    property_type = models.ForeignKey(PropertyType, on_delete=models.SET_NULL, null=True)
    property_neighborhood = models.ForeignKey(PropertyNeighborhood, on_delete=models.SET_NULL, null=True)
    property_type_price_range = models.ForeignKey(PropertyPricerange, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.name)


class PropertyImage(models.Model):
    id = models.AutoField(primary_key=True)
    property_listing_image_main = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    property_listing_image_All = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    property_id = models.ForeignKey(Property, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.property_id)


class Profile(models.Model):
    profile_image = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    name = models.CharField(max_length=50)
    phonenumber = models.IntegerField(max_length=10)
    email = models.EmailField(max_length=50)
    address = models.TextField(max_length=50)


class Search(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(default=timezone.now)
    property_type = models.ForeignKey(PropertyType, on_delete=models.SET_NULL, null=True)
    property_neighborhood = models.ForeignKey(PropertyNeighborhood, on_delete=models.SET_NULL, null=True)
    property_type_price_range = models.ForeignKey(PropertyPricerange, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.id)


class Event(models.Model):
    picture = models.ImageField(upload_to='media/property_images/%Y/%m/%d/', blank=True)
    description = models.TextField(max_length=500)

home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Property, Event, Profile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords don't match")
        return confirm_password

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['name','status', 'description', 'address', 'bedrooms', 'bathrooms', 'square_feet', 'price',
                  'featured_property', 'property_image_main', 'property_image_1', 'property_image_2',
                  'property_image_3', 'property_type', 'property_neighborhood', 'property_type_price_range']


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['picture', 'description']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image', 'phonenumber', 'email', 'address']

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Property, PropertyImage, PropertyType, PropertyNeighborhood, PropertyPricerange, Search, Profile, \
    Event
from .forms import RegistrationForm, PropertyForm, EventForm, ProfileForm
from django.urls import reverse
import os
from django.utils import timezone
from django.db.models import Count
from django.http import HttpResponse


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            error_message = "Invalid login credentials"
            return render(request, 'registration/login.html', {'error_message': error_message})
    return render(request, 'registration/login.html')


def logout_view(request):
    logout(request)
    return redirect('login')


def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', {'form': form})


def home_view(request):
    # if not request.user.is_authenticated:
    #     return redirect('login')

    # featured_Property = Property.objects.get(featured_property=True)
    #  images = PropertyImage.objects.filter(property_id=featured_Property.id)
    # return render(request, 'home.html', {'property': featured_Property,
    # 'images': images})
    properties = Property.objects.get(featured_property=True)

    context = {
        'properties': properties,
    }
    return render(request, 'home.html', context)


def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home:event')
    else:
        form = EventForm()
    return render(request, 'add_event.html', {'form': form})


def event_view(request):
    events = Event.objects.all()
    context = {'events': events}
    return render(request, 'event.html', context)


def profile_view(request):
    profile = get_object_or_404(Profile)
    context = {'profile': profile}
    return render(request, 'profile.html', context)


def listing_view(request):
    listings = Property.objects.filter(flag=True)
    context = {'listings': listings}
    return render(request, 'listings.html', context)


def detail_view(request, pk):
    details = get_object_or_404(Property, pk=pk)
    context = {'details': details}
    return render(request, 'details.html', context)


def add_property(request):
    if request.method == 'POST':
        form = PropertyForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['featured_property']:
                # Set existing featured property to False
                Property.objects.filter(featured_property=True).update(featured_property=False)
            form.save()
            return redirect('home:listings')
    else:
        form = PropertyForm()
    return render(request, 'add_property.html', {'form': form})


def edit_property(request, pk):
    property = Property.objects.get(id=pk)
    if request.method == 'POST':
        form = PropertyForm(request.POST, request.FILES, instance=property)
        if form.is_valid():
            if form.cleaned_data['featured_property']:
                # Set existing featured property to False
                Property.objects.filter(featured_property=True).update(featured_property=False)
            form.save()
            return redirect('home:listings')
    else:
        form = PropertyForm(instance=property)
    return render(request, 'edit_property.html', {'form': form})


def property_search(request):
    property_types = PropertyType.objects.all()
    neighborhoods = PropertyNeighborhood.objects.all()
    price_ranges = PropertyPricerange.objects.all()
    properties = Property.objects.filter(flag=True)

    searched_property = request.GET.get('property_type')
    searched_neighbourhood = request.GET.get('property_neighborhood')
    searched_pricerange = request.GET.get('property_price_range')

    if request.GET.get('property_type'):
        properties = properties.filter(property_type=request.GET.get('property_type'))
        Search.objects.create(date=timezone.now(), property_type_id=request.GET.get('property_type'))
    elif request.GET.get('property_neighborhood'):
        properties = properties.filter(property_neighborhood=request.GET.get('property_neighborhood'))
        Search.objects.create(date=timezone.now(), property_neighborhood_id=request.GET.get('property_neighborhood'))
    elif request.GET.get('property_price_range'):
        properties = properties.filter(property_type_price_range=request.GET.get('property_price_range'))
        Search.objects.create(date=timezone.now(), property_type_price_range_id=request.GET.get('property_price_range'))
    context = {
        'property_types': property_types,
        'neighborhoods': neighborhoods,
        'price_ranges': price_ranges,
        'properties': properties,
        'searched_property': searched_property,
        'searched_neighbourhood': searched_neighbourhood,
        'searched_pricerange': searched_pricerange,
    }

    return render(request, 'search.html', context)


def generate_report(request):
    results = None

    if request.method == 'GET':
        # Get the search criteria from the request parameters
        report_type = request.GET.get('report_type')
        month = request.GET.get('month')
        year = request.GET.get('year')

        # Filter the results based on the report type
        if report_type == 'property_type':
            results = Search.objects.filter(
                date__month=month,
                date__year=year,
                property_type_id__isnull=False
            ).values('property_type__property_type_name').annotate(count=Count('id'))
        elif report_type == 'neighborhood_type':
            results = Search.objects.filter(
                date__month=month,
                date__year=year,
                property_neighborhood__id__isnull=False
            ).values('property_neighborhood__property_neighborhood_name').annotate(count=Count('id'))
        elif report_type == 'price_range_type':
            results = Search.objects.filter(
                date__month=month,
                date__year=year,
                property_type_price_range_id__isnull=False
            ).values('property_type_price_range__property_price_range_name').annotate(count=Count('id'))


    return render(request, 'report.html', {'results': results})


def enquire_view(request):
    return render(request, 'enquire.html')


def edit_profile(request):
    profile = Profile.objects.get()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('home:profile')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'edit_profile.html', {'form': form})

def remove_listing(request, property_id):
    property = Property.objects.get(id=property_id)
    property.flag = False
    property.save()
    return redirect('home:listings')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CK Real Estate</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}" type="text/css">
    <style>
		.navbar-nav .nav-link {
        color: black;
        font-weight: bold;
    }
    </style>
    <script>
    function openEnquiryForm() {
      document.getElementById("enquiryOverlay").style.display = "block";
    }

    function closeEnquiryForm() {
      document.getElementById("enquiryOverlay").style.display = "none";
    }
  </script>
</head>
<body id="body" background="{% static 'img/ck_background.png' %} ">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top"">
        <a class="navbar-brand" href="#"><img style="width: 60px"  src="{% static 'img/ck_logo.png' %}" alt="Logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:listings' %}">Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:property_search' %}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:event' %}">Events</a>
                </li>
                {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'home:generate_report' %}">Reports</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'home:add_property' %}">Add Property</a>
                     </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'home:add_event' %}">Add Event</a>
                     </li>
                {% endif %}
            </ul>


            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>

{#    TODO: this is not currently a functional code, just a reference for future work.#}
    {% block content %}
{#      <h1>Welcome to the Home page!</h1>#}
{#      <p>This is the home page of our site. You can navigate to other pages using the links below:</p>#}
{#      <ul>#}
{#        <li><a href="{% url 'home' %}">Home</a></li>#}
{#        <li><a href="{% url 'login' %}">Login</a></li>#}
{#        <li><a href="{% url 'logout' %}">Logout</a></li>#}
{#        <li><a href="{% url 'register' %}">Register</a></li>#}
{#      </ul>#}
    {% endblock %}

</body>
</html>

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .image-container {
            display: flex; /* Use flexbox to create a flexible container */
            justify-content: center; /* Center-align the images horizontally */
            align-items: flex-start; /* Align the images to the top */
            flex-wrap: wrap; /* Allow wrapping of images to multiple lines if needed */
        }

        .image-container img {
            flex: 0 0 200px; /* Set a fixed width and height for each image */
            height: 200px;
            margin: 10px;
            margin-right: 20px;
        }

        .container {
            display: grid; /* Use grid layout to arrange the columns */
            grid-template-columns: 1fr 1fr; /* Two equal columns */
            justify-items: center; /* Center-align the items horizontally */
            gap: 10px;
            max-width: 1000px; /* Add some gap between the columns */
            margin: 0 auto;
        }

        .box:last-child {
            margin-right: 0;
        }

        .box {
            padding: 10px; /* Add some padding to the boxes */
            line-height: 15px;
            font-weight: bold;
        }

        .box.left-box {
            grid-column: 1 / span 2; /* Place the left box in the first column */

        }

        .box.right-box {
            grid-column: 3 / span 2; /* Place the right box in the second column */
        }

        .button-container {
            display: flex; /* Use flexbox to align the buttons */
            justify-content: left; /* Align buttons with space between them */
            margin-top: 20px;
            margin-left: 500px /* Add some margin to separate from the boxes */
        }

        .button-container button {
            flex: 0 0 auto;
            margin-right: 200px; /* Prevent buttons from growing or shrinking */
        }

        .container {
              display: flex;
              justify-content: space-between;
              align-items: center;
              /* other styles */
            }

        .actions {
              display: flex;
            }

        .actions a,
        .actions button {
              margin-left: 150px; /* Add some space between the link and the button */
            }

    </style>
    <div class="image-container">
        <div class="col-2">
            {% if details.property_image_main %}
                <img src="{{ details.property_image_main.url }}" style="width: 230px; height: 200px">
            {% else %}
                <img src="{% static 'img/default.png' %}" style="width: 300px; height: 200px">
            {% endif %}
        </div>
        <div class="col-2">
            {% if details.property_image_1 %}
                <img src="{{ details.property_image_1.url }}" style="width: 230px; height: 200px">
            {% else %}
                <img src="{% static 'img/default.png' %}" style="width: 300px; height: 200px">
            {% endif %}
        </div>
        <div class="col-2">
            {% if details.property_image_2 %}
                <img src="{{ details.property_image_2.url }}" style="width: 230px; height: 200px">
            {% else %}
                <img src="{% static 'img/default.png' %}" style="width: 300px; height: 200px">
            {% endif %}
        </div>
        <div class="col-2">
            {% if details.property_image_3 %}
                <img src="{{ details.property_image_3.url }}" style="width: 230px; height: 200px">
            {% else %}
                <img src="{% static 'img/default.png' %}" style="width: 300px; height: 200px">
            {% endif %}
        </div>
    </div>
    <br>
    <div class="container">
        <div class="box left-box">
            <h5><b>Description: {{ details.description }}</b></h5><br><br>
            <h5><b>Name: {{ details.name }}</b></h5><br><br>
            <h5><b>Status : {{ details.status }}</b></h5><br><br>
            <h5><b>Address : {{ details.address }}</b></h5><br><br>
            <h5><b>Number of Bedrooms: {{ details.bedrooms }}</b></h5><br><br>
            <h5><b>Size in sqft: {{ details.square_feet }}</b></h5><br><br><br>

        </div>
        <div class="box right-box">
            <h5><b>Property type: {{ details.property_type }}</b></h5><br><br>
            <h5><b>Property Neighborhood: {{ details.property_neighborhood }}</b></h5><br><br>
            <h5><b>Price: ${{ details.price }}</b></h5><br><br>
            <h5><b>Number of Bathrooms: {{ details.bathrooms }}</b></h5><br><br>
            <h5><b>Featured Property: {{ details.featured_property }}</b></h5><br><br><br>
        </div>
    </div>
    <div class="container">
        <div class="actions">
            <a href="#" onclick="openEnquiryForm()">
                <button class="btn btn-lg btn-viewDetails" style="font-weight: bold;background-color: #e5a87a;">Enquire
                    about Property
                </button>
            </a>
        </div>
        <div class="actions">
            <a href="{% url 'home:listings' %}">
                <button class="btn btn-lg btn-viewDetails" style="font-weight: bold">Back</button>
            </a>
        </div>
    </div>
    <div id="enquiryOverlay"
         style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.5);">
        <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: #fff; padding: 20px;">
            <a href="#" onclick="closeEnquiryForm()">Close</a>
            {% include 'enquire.html' %}
        </div>
    </div>
    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'home:edit_property' details.id %}"
           style="position: absolute; top: 70px; right: 10px;">
        <button style="font-weight: bold">Edit Property</button>

        <form action="{% url 'home:remove_listing' details.id %}" method="POST" style="display: inline">
            {% csrf_token %}
            <button style="font-weight: bold; background-color: red;"
                    onclick="return confirm('Are you sure you want to remove the listing from the page?')">Remove
                Listing
            </button>
        </form>

    {% endif %}

{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <h1>Edit Profile</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>

    </head>
<body>

</body>
</html>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <html lang="en">

        <body>
        <div><br/></div>
        <div class="container">
                    <div class="row">
                        <div class="col-5 col-xl-5">
                             <div>
                                <div>

                                    <h1> Find your Dream Home !!</h1>


                                </div>
                                 <div class="col-9" style="padding-bottom: 5%;">
                                    <p style="font-weight: bold;font-size: 18px">CK Real Estate is a real estate company that specializes in selling and leasing residential and
                                        commercial
                                        properties. The company is based in the United States and has a team of expirienced real estate
                                        professionals who are dedicated to providing excellent service to their client.</p>
                                 </div>
                                 <div class="col-9">
                                    <P style="font-weight: bold; font-size: 18px">CK Real Estate is committed to providing personalized service to each of its clients. The company takes
                                        the
                                        time to understand the unique needs and goals of each client and works to develop a customized stratergy
                                        to
                                        help them achieve their real estate objectives. With a focus on building long-term relationships with
                                        its
                                        client, CK Real Estate is dedicated to providing exceptional service that exceeds expectations</p>
                                 </div>
                            </div>
                        </div>
            <div class="col-7" >
                <div class="section-2">
                                    <div>
                                            <u><h2>
                                                <span style="background-color: #cc9900; padding-right: 15px;color: black">Featured Property
                                                </span>
                                            </h2></u>
                                    </div>

                                        <img class="homeimage" src="{% if properties.property_image_main %}{{ properties.property_image_main.url }}
                                                  {% else %}
                                                    {% static "img/no_image.png" %}
                                                  {% endif %}">
{#                                    <img class="homeimage" src="{{ properties.property_image_main }}" alt="{{ property.name }}">#}
                                    <p> <b>{{ properties.name }}</b></p>
                                    <div>
                                        <p>Price: ${{ properties.price }}</p>
                                    </div>
                                    <div>
                                        <p>Bedrooms: {{ properties.bedrooms }}</p>
                                        <p>Bathrooms: {{ properties.bathrooms }}</p></div>
                                    <div>
                                        <p>Square Feet: {{ properties.square_feet }}</p>
                                        <p>Location : {{ properties.address }}</p>
                                        <hr>
                                    </div>
{#                                {% endfor %}#}
                        <a href="{% url 'home:details' properties.id%}">
                            <button class="btn btn-lg btn-viewDetails" style="font-weight: bold">View Details</button>
                        </a>
                    </div>
            </div>
        </div>
       </div>
    </body>

    </html>
    </div>

{% endblock %}

templates/listings.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>

 <title>Cards</title>
</head>

<style type="text/css">


*{
 margin: 0px;
 padding: 0px;
}
body{
 font-family: arial;
}
.main{

 margin: 2%;
}

.card{
     width: 15%;
     display: inline-block;
     box-shadow: 2px 2px 20px black;
     border-radius: 5px;
     margin: 2%;
    }

.image img{
  width: 100%;
  border-top-right-radius: 5px;
  border-top-left-radius: 5px;

 }



.title{

  text-align: center;
  padding: 10px;

 }

h1{
  font-size: 20px;
 }

.des{
  padding: 3px;
  text-align: center;

  padding-top: 10px;
        border-bottom-right-radius: 5px;
  border-bottom-left-radius: 5px;
}
button{
  margin-top: 40px;
  margin-bottom: 10px;
  background-color: white;
  border: 1px solid black;
  border-radius: 5px;
  padding:10px;
}
button:hover{
  background-color: black;
  color: white;
  transition: .5s;
  cursor: pointer;
}
/* Style for the "Add Property" button */
.add-property-btn {
  position: absolute;
  top: 20px;
  right: 20px;
}
</style>

 <body background="bg.png">

<div class="main">

    <!--cards -->
  {% for listing in listings %}
    <div class="card">
        <div class="image">
            <img width="250" height="200" src="{{ listing.property_image_main.url }}">
        </div>
        <div class="title">
            <h1 class="property-name"><b>{{ listing.name }}</b></h1>
            <p class="property-price"><b>Price:</b> {{ listing.price }}</p>
            <p class="property-info"><b>Bedrooms:</b> {{ listing.bedrooms }} | <b>Bathrooms:</b> {{ listing.bathrooms }}</p>
            <p class="property-address"> <b>Address: </b>{{ listing.address }}</p>
            <p class="property-status"><b>Status: </b> {{ listing.status }}</p>
            <div class="des">
                <a href="{% url 'home:details' listing.id%}">
                    <button class="btn btn-lg btn-viewDetails" style="font-weight: bold">View Details</button>
                </a>
            </div>
        </div>
    </div>
{% endfor %}
</div>
</body>
</html>

{% endblock %}